config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'

  get 'users/new'
  get 'users/create'


  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :admin do 
    resources :users
  end

  root to: 'movies#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews 
  has_secure_password

  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: { in: 6..20 }, on: :create     
  #validte password comes from bcrypt, the database field is actually password_digest

  def full_name
    "#{firstname} #{lastname}"
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    if current_user.admin?
      @users = User.all.page(params[:page]).per(10)
      render :index
    else
      not_admin_redirect
    end
  end

  def show 
    if current_user.admin?
      @user = User.find(params[:id])
      render :show
    else
      not_admin_redirect
    end
  end

  def new
    if current_user.admin?
      @user = User.new
    else
      not_admin_redirect
    end
  end

  def edit
    if current_user.admin? 
      @user = User.find(params[:id])
    else
      not_admin_redirect
    end
  end

  # @user is a new movie passing in the parameters from this create page
  # if it properly saves, go to the all movies page, otherwise go to the 'new' page again
  def create
    if current_user.admin?
      @user = User.new(user_params)
      if @user.save
        redirect_to admin_users_path, notice: "User with email: #{@user.email} was successfully created!"
      else
        render :new # TODO: this needs to render the admin/new not the regular
      end
    else
      not_admin_redirect
    end
  end 

  def destroy
    if current_user.admin?
      @user = User.find(params[:id])
      @user.destroy
      UserMailer.deletion_email(@user)
      redirect_to admin_users_path, notice: "User #{@user.email} was successfully deleted."
    else
      not_admin_redirect
    end
  end

  def update
    if current_user.admin?
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        redirect_to admin_user_path(@user), notice: "User #{@user.email} was successfully updated."
      else
        render :edit
      end
    else
      not_admin_redirect
    end
  end

  protected

  def user_params
    params.require(:user).permit(
      :email, :firstname, :lastname, :password, :password_confirmation, :admin
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, success: "Thanks for joining, #{@user.firstname}!"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

  def not_admin_redirect
    redirect_to root_path, notice: "Get out! You must be an admin to view that page!"
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>      
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.check_box :admin %> <%= f.label :admin %> 
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<%= link_to "Back to this user", admin_user_path(@user) %>

<h2>Edit this movie.</h2>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Users</h1>
<%= link_to "Back to home page!", root_path, class: "btn btn-md btn-success" %>

<%= paginate @users %>

<% @users.each do |user| %><br>
  <h3 class="admin-view-user"><%= link_to user.email, admin_user_path(user) %></h3>
  <p><%= user.firstname %>, <%= user.lastname %></p>
<% end %>

app/views/admin/users/new.html.erb
<h1>Create a New User</h1>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<%= link_to "Back to admin user page", admin_users_path, class: "btn btn-md btn-success" %><br>

<h3>Email: </h3><h4><%= @user.email %></h4>
<h3>First Name:</h3> <h4><%= @user.firstname %></h4> <h3>Last Name:</h3> <h4><%= @user.lastname %></h4>
<h4><h3>Password - (admin purposes): </h3><%= @user.password_digest %></h4>
<h2><%= link_to "Edit", edit_admin_user_path(@user) %>, <%= link_to "Delete", admin_user_path(@user), method: :delete, data: {confirm: "You sure?"} %></h2> 