config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'

  get 'users/new'
  get 'users/create'


  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :admin do 
    resources :users
  end

  root to: 'movies#index'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<!-- Omit for now, may need later but footer currently not utilized-->
<!--   <small>
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log Out", session_path("current"),method: :delete %>)
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
    <% if current_user && current_user.admin == true %>
      Admin menu <%= link_to "All Users", admin_users_path %>
    <% end %>
  </small> -->
</footer>

app/views/layouts/_masthead.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <section class="row">
    <div class="hvr-float col-sm-3">
      <h2><%= link_to "Rotten Mangoes", root_path %></h2>
    </div>
    <div class="col-sm-9 nav-right-div">
      <h5 class="navbar-right">   
      <% if current_user %>
        Hey there, <%= current_user.full_name %> [<%= link_to " Log Out ", session_path("current"),method: :delete %>]
      <% else %>
        <%= link_to " Log In ", new_session_path %> | <%= link_to " Sign Up ", new_user_path %>
      <% end %>
      <% if current_user && current_user.admin == true %>
        Admin Menu: <%= link_to " All Users ", admin_users_path %>
      <% end %>
      </h5> 
    </div>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangoes</title>
<!--   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"> -->
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Patua+One' rel='stylesheet' type='text/css'>
  <!-- <link href="https://fonts.googleapis.com/css?family=Lora:700" rel="stylesheet"> -->
  <%= stylesheet_link_tag    'application', media: 'all'  %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/masthead' %>
  <% flash.each do |key, value| %>
    <div class="flash <%= key %> alert alert-success">
      <%= content_tag(:div, value) %><br>
    </div>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>